// VARIABLES
var result;
var input;
var started;

// USER CLICS AN OPERATOR 1ST TIME --> INPUT GOES TO RESULT AND SAVE THE OPERATOR (+ - / X)

// USER CLICS AN OPERATOR 2NDO AND BEYOND TIME --> DEPENDING ON OPERATOR, THE APP DO THE OPERATION WITH RESULT AND INPUT AND SAVE THE OPERATOR
// WE CONTROL THE XTH TIME WITH A SWITCH (STARTED)

// USER CLICS AN OPERATOR AFTER CLICING ANOTHER OPERATOR AND WITH NO INPUT VALUE
// MAYBE AN ALERT OR AN ERROR MESSAGE

// USER CLICS = --> DEPENDING ON OPERATOR, THE APP DO THE OPERATION WITH RESULT AND INPUT; THEN, RETURN RESULT